FROM alpine:3.6

COPY frp/frpc /usr/local/bin/
COPY frp/frpc_full.ini /etc/frpc.ini
COPY run.client.sh /usr/local/bin/run.sh

RUN sed -i 's/^log_file .*/log_file\ =\ \/data\/frpc.log/' /etc/frpc.ini && \
    chmod +x /usr/local/bin/frpc && \
    chmod +x /usr/local/bin/run.sh && \
    mkdir /data/

CMD /usr/local/bin/run.sh
